# fly.toml app configuration file generated for educatalogue on 2023-07-12T07:26:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "educatalogue"
primary_region = "waw"

[build]
  image = "javiaxum/educatalogue:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "939267735243899"
  Cloudinary__CloudName = "dnvpzd2ne"
  Facebook__AppId = "1181277965779433"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
